### ISSUE TITLE
Weblab as backend for a Jupiter book.

### ISSUE THREAD

**Issue by martinclaus** [weblab-kiel/environments#2]
It is possible to use a jupyter hub to launch notebooks being part of a jupyter book. At the moment I am not sure what needs to be done.

**Comment by willirath** [comment]
See Ryan's book and especially the ocean.pangeo.io links for inspiration.

**Comment by martinclaus** [comment]
nbgitpuller was already installed on weblab, however the server extension needed to be enabled (jupyter is too old on weblab):
```bash
jupyter serverextension enable nbgitpuller --sys-prefix
```

**Comment by willirath** [comment]
On Weblab, it works out of the box. Use the link generator here https://jupyterhub.github.io/nbgitpuller/link.html <https://jupyterhub.github.io/nbgitpuller/link.html> to nbgitpull the materials. Link:

https://WEBLAB-URL/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fgeomar-tm%2Fpython-intro-201804&urlpath=lab%2Ftree%2Fpython-intro-201804%2Fsession-01_part-01_intro_to_python.ipynb

**Comment by willirath** [comment]
Correction (Didn't see your comment.): Doesn't work out of the box.

**Comment by martinclaus** [comment]
nbgitpuller was already installed on weblab, however the server extension needed to be enabled (jupyter is too old on weblab):
```bash
jupyter serverextension enable nbgitpuller --sys-prefix
```

**Comment by martinclaus** [comment]
After enabling the server extension, weblab now works as an backend for jupyter books.
