### ISSUE TITLE
Gravmag env does not build

### ISSUE THREAD

**Issue by willirath** [weblab-kiel/environments#9]
@nholzrichter There's a conflict for
```yaml
...
- pyshtools
- gmt==6.0.0
- ...
```
because [`pyshtools` requires `gmt >=6.1.1`](https://github.com/conda-forge/pyshtools-feedstock/blob/master/recipe/meta.yaml#L41). Can we relax the pinned version of `gmt`?

**Comment by willirath** [comment]
Alternatively, we may be able to go with pinning `pyshtools=4.6.2`. I'll try that.

**Comment by nholzrichter** [comment]
Gmt 6.1.1. Is also Allright for all

************************************************************************ Dr. Nils Holzrichter, Dipl.-Geophys. Institute of Geosciences, Depart. Geophysics Christian-Albrechts-University Kiel Otto-Hahn-Platz 1, 24118 Kiel, Germany Phone: +49 (0)431 / 880 3880 Fax: +49 (0)431 / 880 4432 Room: 213 ***@***.*** https://www.satellitengeophysik.uni-kiel.de/de/mitarbeiter/nils_holzrichter ***********************************************************

Am 27. April 2021 12:32:08 MESZ schrieb Willi Rath ***@***.***>:
***@***.*** There's a conflict for
